name: sistema_tareas_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.0.11
  json_annotation: ^4.7.0
  logging: ^1.1.0 # Agregado para el manejo de logs
  provider: ^6.1.2 # Agregado para el manejo de estado y inyección de dependencias
  flutter_localizations:
    sdk: flutter # Para la localización en múltiples idiomas
  http: ^0.14.0 # Ejemplo de paquete para realizar solicitudes HTTP
  shared_preferences: ^2.0.6 # Ejemplo de paquete para manejar preferencias compartidas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/usuarios.json

